export const RequestExportList = [
  {
    id: "001",
    createAt: new Date("2024-09-22"),
    createBy: "Alex",
    orderId: "001",
    status: 0,
    quantity: 20,
  },
  {
    id: "002",
    createAt: new Date("2024-09-22"),
    createBy: "June",
    orderId: "002",
    status: 1,
    quantity: 30,
  },
  {
    id: "003",
    createAt: new Date("2024-09-22"),
    createBy: "Alex",
    orderId: "003",
    status: 2,
    quantity: 40,
  },
  {
    id: "004",
    createAt: new Date("2024-09-23"),
    createBy: "Mike",
    orderId: "004",
    status: 0,
    quantity: 20,
  },
  {
    id: "005",
    createAt: new Date("2024-09-23"),
    createBy: "Sara",
    orderId: "005",
    status: 1,
    quantity: 30,
  },
  {
    id: "006",
    createAt: new Date("2024-09-24"),
    createBy: "David",
    orderId: "006",
    status: 2,
    quantity: 20,
  },
  {
    id: "007",
    createAt: new Date("2024-09-24"),
    createBy: "Emma",
    orderId: "007",
    status: 0,
    quantity: 20,
  },
  {
    id: "008",
    createAt: new Date("2024-09-25"),
    createBy: "John",
    orderId: "008",
    status: 1,
    quantity: 30,
  },
  {
    id: "009",
    createAt: new Date("2024-09-25"),
    createBy: "Rachel",
    orderId: "009",
    status: 2,
    quantity: 20,
  },
  {
    id: "010",
    createAt: new Date("2024-09-26"),
    createBy: "Paul",
    orderId: "010",
    status: 0,
    quantity: 20,
  },
  {
    id: "011",
    createAt: new Date("2024-09-26"),
    createBy: "Lily",
    orderId: "011",
    status: 1,
    quantity: 30,
  },
  {
    id: "012",
    createAt: new Date("2024-09-27"),
    createBy: "Tom",
    orderId: "012",
    status: 2,
    quantity: 20,
  },
];

export const InventoryListData = [
  {
    id: "001",
    name: "Chicken",
    stockLevel: 20,
    unit: "kg",
    supplier: "Nesson",
    status: 0,
  },
  {
    id: "002",
    name: "Pork",
    stockLevel: 0,
    unit: "kg",
    supplier: "Visson",
    status: 1,
  },
  {
    id: "003",
    name: "Beef",
    stockLevel: 20,
    unit: "kg",
    supplier: "Visson",
    status: 2,
  },
  {
    id: "004",
    name: "Salad",
    stockLevel: 50,
    unit: "kg",
    supplier: "FreshFarm",
    status: 0,
  },
  {
    id: "005",
    name: "Chicken",
    stockLevel: 30,
    unit: "kg",
    supplier: "Nesson",
    status: 1,
  },
  {
    id: "006",
    name: "Pork",
    stockLevel: 10,
    unit: "kg",
    supplier: "Visson",
    status: 2,
  },
  {
    id: "007",
    name: "Beef",
    stockLevel: 15,
    unit: "kg",
    supplier: "Visson",
    status: 0,
  },
  {
    id: "008",
    name: "Salad",
    stockLevel: 100,
    unit: "kg",
    supplier: "FreshFarm",
    status: 1,
  },
  {
    id: "009",
    name: "Chicken",
    stockLevel: 10,
    unit: "kg",
    supplier: "Nesson",
    status: 2,
  },
  {
    id: "010",
    name: "Pork",
    stockLevel: 50,
    unit: "kg",
    supplier: "Visson",
    status: 0,
  },
  {
    id: "011",
    name: "Beef",
    stockLevel: 80,
    unit: "kg",
    supplier: "Visson",
    status: 1,
  },
  {
    id: "012",
    name: "Salad",
    stockLevel: 20,
    unit: "kg",
    supplier: "FreshFarm",
    status: 2,
  },
  {
    id: "013",
    name: "Chicken",
    stockLevel: 40,
    unit: "kg",
    supplier: "Nesson",
    status: 0,
  },
  {
    id: "014",
    name: "Pork",
    stockLevel: 25,
    unit: "kg",
    supplier: "Visson",
    status: 1,
  },
  {
    id: "015",
    name: "Beef",
    stockLevel: 100,
    unit: "kg",
    supplier: "Visson",
    status: 2,
  },
];
